#!/usr/bin/env python

import rospy
import sys
from std_msgs.msg import String
import dynamic.rosdy as rosdy

def callback(data):
	rospy.loginfo(rospy.get_name()+"I heard %s",data.data)

if __name__ == '__main__':
	rospy.init_node('listen')
	sub = rosdy.Subscriber('1',String, 'String')
	print 'here'
	sub.subscribe(callback)
	
