#!/usr/bin/env python
import rospy
from std_msgs.msg import String
import dynamic.rosdy as rosdy

def talker():
	pub = rosdy.Publisher('1', String, 'String')
	i=0
	r = rospy.Rate(1)
	while not rospy.is_shutdown():
		if pub.checkForTopic():
			pub.publish(String('here %i'%(i)))
			i+=1
		r.sleep()

if __name__ == '__main__':
    rospy.init_node('talk')
    try:
        talker()
    except rospy.ROSInterruptException: pass
